apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "movie-be.fullname" . }}
  labels:
    app: {{ include "movie-be.name" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ include "movie-be.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "movie-be.name" . }}
    spec:
      containers:
        - name: api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
